apiVersion: v1
kind: DeploymentConfig
metadata:
  name: mygovbc-msp-service
  namespace: gcpe-mygovbc-msp-dev
  selfLink: /oapi/v1/namespaces/gcpe-mygovbc-msp-dev/deploymentconfigs/mygovbc-msp-service
  uid: 4eb4e424-d912-11e6-89a5-0050568379a2
  generation: 11
  creationTimestamp: '2017-01-12T21:58:53Z'
  labels:
    app: mygovbc-msp-service
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources:
  triggers:
    -
      type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - mygovbc-msp-service
        from:
          kind: ImageStreamTag
          namespace: gcpe-mygovbc-msp-dev
          name: 'mygovbc-msp-service:latest'
        lastTriggeredImage: '172.50.0.2:5000/gcpe-mygovbc-msp-dev/mygovbc-msp-service@sha256:6317e76c524051f4b4f9029f5ee4ab365cbe5c64cb76362a4d941e41f74b5010'
    -
      type: ConfigChange
  replicas: 1
  test: false
  selector:
    deploymentconfig: mygovbc-msp-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mygovbc-msp-service
        deploymentconfig: mygovbc-msp-service
    spec:
      containers:
        -
          name: mygovbc-msp-service
          image: '172.50.0.2:5000/gcpe-mygovbc-msp-dev/mygovbc-msp-service@sha256:6317e76c524051f4b4f9029f5ee4ab365cbe5c64cb76362a4d941e41f74b5010'
          ports:
            -
              containerPort: 8080
              protocol: TCP
          env:
            -
              name: TARGET_URL
              value: ''
            -
              name: TARGET_HEADER_HOST
              value: ''
            -
              name: TARGET_USERNAME_PASSWORD
              value: ''
          resources:
            requests:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
status:
  latestVersion: 8
  observedGeneration: 11
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  details:
    message: 'caused by an image change'
    causes:
      -
        type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: gcpe-mygovbc-msp-dev
            name: 'mygovbc-msp-service:latest'
